version: '3.8'
services:
  weather-report-dev:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - weatherreport
networks:
  weatherreport: